export const GET_TWEET = 'GET_TWEET'
export const ADD_TWEET = 'ADD_TWEET'
export const DELETE_TWEET = 'DELETE_TWEET'
export const EDIT_TWEET = 'EDIT_TWEET'
export const ACTUAL_TWEET = 'ACTUAL_TWEET'
export const VALIDATE_FORM = 'VALIDATE_FORM'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const SHOW_SPINNER = 'SHOW_SPINNER'
export const HIDE_SPINNER = 'HIDE_SPINNER'
export const ADD_PROFILE = 'ADD_PROFILE'
export const REMOVE_PROFILE = 'REMOVE_PROFILE'
export const GET_ACTUAL_TW = 'GET_ACTUAL_TW'
export const GET_LOGIN = 'GET_LOGIN'
export const GET_SIGNUP = 'GET_SIGNUP'

